### ISSUE TITLE
Update only the pinned deps for new dependency, not all

### ISSUE THREAD

**Issue by mbertheau** [nvie/pip-tools#118]
I was thinking about the workflow in using pip-compile for an application A. You've set it all up and pinned all your requirements. Now you want to add a feature and need a new library L for that. You add it to requirements.in and run pip-compile. This will add L and its dependencies to requirements.txt. It will also update all your other dependencies to the newest versions. This migth be more than you asked for when you just wanted to add another dependency.

It might be desirable to have a way to tell pip-compile to only update/add pinned dependencies if it is necessary for the new non-pinned dependency.

**Comment by estan** [comment]
I agree. I would like it if `pip-compile` took something like a `-d` option with a list of abstract dependencies to update. Then I could update say `numpy` selectively with `pip-compile -d numpy`. It should error if `numpy` is not declared in `requirements.txt`, or if upgrading just `numpy` is impossible without also upgrading some other requirement in `requirements.txt` (due to shared dependencies).

**Comment by estan** [comment]
I was thinking, as a workaround right now, would it be possible to:

1. Temporarily pin all dependencies you want to keep fixed in requirements.in to whatever is in requirements.txt currently.
2. Add your new dependency to requirements.in 
3. Run `pip-compile`
4. Undo changes in 1, and depending on how you want to maintain the new dep, either pin it in requirements.in or leave it as is.

Would that work? Then `pip-compile` would error if the new dep could not be added because of conflicting deps. The same approach could be used if you just want to update an existing dep without touching the others.

**Comment by estan** [comment]
I guess my above approach won't really work, since I guess it might still do unwanted updates of transient (indirect) dependencies in step 3? So some support in `pip-compile` for selectively updating one or more dependencies while keeping others fixed (if possible) would still be nice.

**Comment by nvie** [comment]
This flow is supported since pip-tools 1.6. It's even the default behaviour now! If you have a requirements.in and requirements.txt file, and you add a new dependency to the .in file and re-run pip-compile, it will only add the new dependency to the .txt file. Similarly, if you remove a dependency, it will remove it (and any nested dependencies that are not used by other packages).

The only way to enforce existing packages to be upgraded these days is to use `pip-compile --upgrade` explicitly. Hope that helps!
