### ISSUE TITLE
pip-review suggesting upgrade to alpha/beta/rc

### ISSUE THREAD

**Issue by kegan** [nvie/pip-tools#135]
pip-review suggesting upgrade to alpha/beta/release candidate. It seems like this happen (not limited to):

* Python 3.4.2
* Python 2.7.9

`$ pip-review`
`Django==1.8a1 is available (you have 1.7.4)`
`ipython==3.0.0rc1 is available (you have 2.4.1)`

**Comment by carschar** [comment]
I can confirm the behavior. I think pip-review should be enhanced to mimic current pip behavior, which is to by default only consider release versions. This means alpha, beta, and rc would not be recommended. This is overriden in pip with the "--pre" flag.

I may take a shot at adding this, if no one else a pull request out yet. It sounds like fun.

**Comment by b4stien** [comment]
Same behaviour here. From a user's perspective it's quite a biggie.

**Comment by nvie** [comment]
I'm happy to merge this is if someone wants to make a pull request for this.

**Comment by b4stien** [comment]
After a quick look: it will not be straightforward.

The fact that a release is a pre-release is not specified on PyPI (see for instance https://pypi.python.org/pypi/SQLAlchemy/1.0.0b5/json). I'm not sure how `pip` is able to handle them. Parsing the version and inferring from there maybe ?

**Comment by b4stien** [comment]
I'm currently working on a PR for this.

It will use https://pypi.python.org/pypi/packaging, do you prefer it vendorized (like pip does) or declared as a dependency?

**Comment by nvie** [comment]
Hi @b4stien, that's great. I'm wondering what "it" refers to? And what do you mean by vendorized/declared-as-dependency exactly?

**Comment by b4stien** [comment]
By "it" I meant "my PR", sorry.

Vendorizing a dependency is the process of copying/pasting its source inside yours. The alternative is to "declare" this dependency for pip/setuptools to grab it at install time (that's what I did in my PR).

**Comment by nvie** [comment]
Hi @b4stien, thanks for that! This weekend I have been trying out a few things that could be changed about the current pip-tools implementation. A _lot_ of the requirement parsing, spec resolving, etc. has been NIH'ed by me when I first wrote this tool and it turns out that most of this logic is also accessible in a reusable fashion inside pip — at least it is now.

One of the current problems with the pip-compile code is that I think it has become way too complicated, and I basically want to rewrite it now that I'm more familiar with pip/packaging/setuptools' code bases, and with the experience of writing it the first time, of course.

My goal is to reuse pip's internals everywhere unless that proves to be impossible. So far, it seems that only the dependency resolver itself is not available in pip, but I think that's pip-tools' core value anyway. All the rest is hacking around or reimplementing concepts that are solved problems in pip.

This means I'm going to rewrite pip-tools' internals quite rigorously. This will mean that I'll also fully adopt the helper classes from packaging, which means we'll have the prerelease issues covered, too.

My plan is to drop support for all pip versions and only support >= 6.1. I hope that by doing this, it will lower maintenance on pip-tools, keep the code much more straight-forward, and we can support all the packaging edge cases a bit better (i.e. no more hacks to support `--find-links`, etc.)

**Comment by wil93** [comment]
Hi, when will this change make it to pypi? The current version of pip-tools does not include it.

**Comment by b4stien** [comment]
It seems @nvie intended to rewrite (or has rewritten, see the `future` branch) a huge part of the project, but it hasn't made its way to PyPI yet.

I ended up using my own fork for this specific matter.

**Comment by chhantyal** [comment]
Also `pip-review --auto` actually installs beta/rc releases. If this is not going to be fixed soon, would be great if we could update docs.

**Comment by blueyed** [comment]
The rewrite mentioned above happened in/via #153.

**Comment by jgonggrijp** [comment]
@b4stien pip-review is now living on as a separate package, see [here](https://pypi.python.org/pypi/pip-review). If you think your pull request is still relevant, please consider submitting it to [my fork](https://github.com/jgonggrijp/pip-review) (develop branch).

**Comment by b4stien** [comment]
@jgonggrijp it is still relevant, I'll try to submit a PR there this week.

**Comment by wil93** [comment]
I'd like to ask, though: if pip-compile does not suggest to upgrade to beta versions (because the `massive-rewrite` branch was merged), then why couldn't pip-review just use pip-compile as a dependency? (wherever pip-review now lives).

Also: from what I undestand, pip-review is now no longer needed (you can just use pip-compile), but I can see how it could still be useful in some cases.

Lastly: is there an official reason from pip-tools' author as of why pip-review was dropped?

**Comment by wil93** [comment]
Nevermind, I found the thread where the author explains the reason: #185.

I also realized that I can just do `pip list --outdated` and it's exactly the same as running `pip-review`. So my question is now: why are we trying to keep pip-review running?

**Comment by b4stien** [comment]
Wow, didn't know about `pip list`! Thank you so much!

It even includes a `--pre` flag and only show stable versions by default.

**Comment by jgonggrijp** [comment]
@wil93 `pip-review` can do something that neither `pip list -o` nor `pip-compile` can do: it can upgrade all outdated packages for you, interactively or fully automatically.

Now, using `pip list -o` and then manually installing the updates that you want may be not much more effort than using `pip-review --interactive`. `pip-review --auto`, on the other hand, is much more convenient, especially because it can also be used in a scripting context. For me, `pip-review --auto` was sufficient reason to create a new repo and a new package for pip-review.

However, if people still think that the pip ecosystem doesn't need pip-review after reading this, I'd like to hear their reasons. I don't want to keep something in the air while people think it isn't needed (mind you, the package was downloaded about 1100 times since I uploaded it one month ago).

**Comment by wil93** [comment]
@jgonggrijp Fair enough. I can see how `--interactive` can be a good reason to keep it. However, consider this. You could:

1. Convert the pip-tools fork to a standard github repository named "pip-review" (I'm not sure if this is hard to do, maybe you should contact github), or just delete it and create it again.
2. Drop every line of code that belonged to pip-tools.
3. Rewrite pip-review as a very simple wrapper to `pip list` (I guess it should be at most 30 lines of code?).

The pip-review package would then still exist, with these advantages:

* The alpha/beta/rc issue would be automatically gone, without intervention, because it would just use `pip list` under the hood.
* It would be simpler to maintain, for the same reason.

Actually, you could even make it a shell script (but then you would lose the possibility of uploading the package to pypi, so I'd stick with python).

> mind you, the package was downloaded about 1100 times since I uploaded it one month ago

I'm not sure how many are aware of `pip list --outdated`.

**Comment by jgonggrijp** [comment]
@wil93 What you describe is possible. However, I don't think it is less effort than sticking with Vincent's existing code for `pip-review` and accepting @b4stien's pull request (which is pretty much ready if I'm right). Personally, I don't really care how the functionality is provided, as long as it is there, and this is not something I want to spend a lot of time on.

I don't mind if somebody else takes up the challenge and implements what you describe. If it works well, I don't even mind if they call it pip-review 2.0 or something like that (though @nvie should probably have a say in that as well). If something better exists I'll be happy to drop the current pip-review package, no feelings hurt. But I want the functionality to exist and as long as I have to do it, I'll take the least effort route.

**Comment by Jc2k** [comment]
I don't use `pip-tools` yet but have been following it on GitHub since i heard of it with a view to use `pip-sync`. This thread has reminded me to get round to using it now the future branch is merged.

My ideal workflow would be to update `requirements.txt` (aided by `pip list -o` or `pip-compile`) and then run `pip-sync`. I  would want to review the changelogs of the projects I'm updating. So i'd want to update my `requirements.txt` then `git diff` before i commit. But then other devs and the prod/stage deployments would use pip-sync on my refreshed `requirements.txt`.

Are these commands roughly equivalent (given a suitably unpinned `requirments.txt`?:

    pip-compile && pip-sync
    pip-review --auto && pip freeze > requirements.txt

Can I tell either of these stuff like 'don't upgrade Django to the next major release'?

@jgonggrijp you said you use `pip-review --auto` is a scripted way. What is that?

(Btw we shouldn't get hung up on the download statistics - they are heavily skewed by indexers and mirrors. A fresh release can get 1,600 downloads just from bots).

**Comment by jgonggrijp** [comment]
@Jc2k No, those commands are not equivalent.

`pip-compile && pip-sync` pins the currently installed versions of your dependencies (presuming you defined your top-level dependencies in `requirements.in`) and uninstalls all non-dependency packages except for pip-tools and pip-review. So if you have SQLAlchemy installed but it is not a dependency of your project, it will be gone after this command.

`pip-review --auto && pip freeze >requirements.txt` **updates** *all* of your packages and then pins *all* of them in your `requirements.txt`. So in this case, SQLAlchemy (if installed) would be updated and pinned regardless of whether it is a dependency or not.

When I said `pip-review --auto` is useful in a scripting context, I meant to say it is currently the most convenient way to update all packages in your virtualenv without human intervention. Suppose you have a virtualenv in which you want to keep all packages up-to-date all the time; you could for example have that by writing a crontab that runs `pip-review --auto` periodically.

As for ideal workflows, I think pip-compile, pip-sync and pip-review augment each other nicely. Suppose your project is in a state where everything works harmoniously. You pin your requirements using `pip-compile` and now you can reproduce your well-balanced set of packages everywhere using `pip-sync`. A few weeks or months later, packages have been updated, some containing important security fixes. You use `pip-review` to get things up-to-date and make sure that everything still works. If it doesn't and you think the update is not worth the trouble of fixing things, you can roll back easily using `pip-sync`. If it does work, or if you decide to fix things until everything does work, you can pin the new set of requirements using `pip-compile`. Rinse and repeat.

**Comment by jgonggrijp** [comment]
@wil93 After re-reading I noticed that you said

> (while, for non-interactive upgrade, there is pip-sync)

I should point out that this is a different kind of upgrading than `pip-review --auto`. The latter always upgrades every package to the latest version available. `pip-sync`, on the other hand, will upgrade a package if it is required and the installed version is older than the version in the `requirements.txt`, but otherwise it will downgrade, uninstall or ignore a package (even though a newer version might be available). Even when `pip-sync` does upgrade a package, it will upgrade it to the version in your `requirements.txt`, which might be older than the latest available version. `pip-sync` makes your environment reflect your `requirements.txt` 100% no matter how outdated it is. These commands really serve very different purposes.

**Comment by jgonggrijp** [comment]
@b4stien In the meanwhile I received a pull request by @rvause which solves this issue. pip-review is now at version 0.4. @nvie I think this ticket can be closed.

**Comment by b4stien** [comment]
@jgonggrijp no problem, glad it's resolved! Gonna leave a comment there.
