### ISSUE TITLE
future: use ~/.cache/pip-tools (XDG)

### ISSUE THREAD

**Issue by blueyed** [nvie/pip-tools#170]
I think the cache folder should be moved into `XDG_CACHE_HOME`.

    XDG_CACHE_HOME = os.environ.get("XDG_CACHE_HOME", os.path.join(HOME, ".cache"))

**Comment by nvie** [comment]
I'm not sure what XDG is, but I don't think it should bleed into pip-tools.

**Comment by grigi** [comment]
XDG_CACHE_HOME is defined by freedesktop.org: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
XDG_CACHE_HOME is what a unix-login users cache-directory should be. pip itself uses it, and is generally considered a good place to put things. IOW, I can setup a server and only provide it one general cache directory with correct permissions.

Since pip itself uses it, you can expect it to be defined wherever pip-tools are used.

**Comment by blueyed** [comment]
@nvie 
Please re-consider - it's a standard and makes it easier for users.
There would also be a lib for Python, but it's rather easy and therefore I have not added it as a dep.

**Comment by nvie** [comment]
My gut feeling says this is an XDG specific thing, that does not apply to all users/envs. Personally, I had never heard of this standard. Windows users may require a different standard. Mac OSX another one. If pip indeed uses this, that's great. Perhaps there's a way of using the pip internals to get this cache dir? Alternatively, we could support a command line flag to set it, though that may not be ideal.

**Comment by grigi** [comment]
Hmm, valid point:
https://github.com/pypa/pip/blob/develop/pip/utils/appdirs.py#L13
That should be it.

**Comment by blueyed** [comment]
@grigi 
Good find.  I agree that we should use this instead.

@nvie 
Should I provide a new/updated PR, or will you do it yourself?

**Comment by nvie** [comment]
I'll add it myself

**Comment by nvie** [comment]
This is addressed in pip-tools==1.0.5 now. Thanks!
