### ISSUE TITLE
pip-compile ignores umask for generated requirements.txt files

### ISSUE THREAD

**Issue by chaoflow** [nvie/pip-tools#268]
requirements.txt files are generated `-rw-------`. They should be created according to the umask.

**Comment by chaoflow** [comment]
sorry for the mess. pip is also not taking umask into account for its .cache/pip files - might be intentionally - and I mistook it for pip-tools.

**Comment by nvie** [comment]
pip-compile "just" creates a file, the OS/Python is responsible for applying the correct umask, not pip-tools.

**Comment by chaoflow** [comment]
OS (touch) and python (open('foo', 'w')) are doing their job.

pip-tools uses boltons AtomicSaver, which creates a [temporary file](https://github.com/nvie/pip-tools/blob/master/piptools/io.py#L84) and then renames it. After that it should apply the correct umask.

**Comment by nvie** [comment]
I believe this should be fixed in the boltons library instead. I want to keep this code vendored in, not branch off from it. Feel free to open an issue on https://github.com/mahmoud/boltons/issues, though. If it gets fixed there, I'll just include it here again. Thanks!

**Comment by mahmoud** [comment]
The umask behavior has changed quite a bit since the early version pip-tools first included, so make sure you have the new version of pip-tools with the new version of [`boltons.fileutils`](https://github.com/mahmoud/boltons/blob/master/boltons/fileutils.py).

I worked with Brian Warner (of buildbot fame) to get an intuitive and secure behavior for the new atomic file save. The only way I can see a file created with those permissions are:

1. The `atomic_save` call explicitly passed those permissions in the `file_perms` argument.
2. There was an existing requirements.txt file with those permissions. boltons' AtomicSaver will copy the permissions of an existing file, which is usually the desired behavior.

In all other cases, the umask is there by default (as @nvie mentioned), and should be respected. [The docs](http://boltons.readthedocs.org/en/latest/fileutils.html#boltons.fileutils.AtomicSaver) talk about this a bit, but [this method](https://github.com/mahmoud/boltons/blob/514d1417d90498858f2617f68d7d40e695674236/boltons/fileutils.py#L310) is pretty short and readable, describing the whole semantics in ~25 lines.

Hope this helps! If not, totally feel free to file an issue on boltons itself. :)

**Comment by nvie** [comment]
I'm sorry, I checked the wrong branch for some reason, assuming AtomicSaver has not seen any changes. The new version looks great to me! I have just included it. Thanks for this awesome library and your quick response, @mahmoud :)

**Comment by nvie** [comment]
This should now be fixed with pip-tools==1.4.2. Let me know if you still experience this issue, @chaoflow!

**Comment by chaoflow** [comment]
@nvi Thank you for the update and release. The issue is fixed.

**Comment by andersk** [comment]
This bug seems to have regressed between pip-tools 3.5.0 and pip-tools 3.6.0.

**Comment by atugushev** [comment]
@andersk yes, there is a related issue #823.
