### ISSUE TITLE
pip-sync upgrades frozen packages to newer versions since 1.4.3

### ISSUE THREAD

**Issue by syphar** [nvie/pip-tools#290]
example requirements.txt 

```
Django==1.8.8 
django-admin-sortable==2.0.9  # has "Django" in install_requires 
``` 

when I call `pip-sync requirements.txt` the command will upgrade Django to `1.9.1` (since 881cd7540f29533d54f515e6a4d6e2bf20856c52 we call `pip install --upgrade django-admin-sortable==2.0.9` which leads to the upgrade here) 

is this wanted behavior?

**Comment by nvie** [comment]
Oh wow, that's definitely not wanted. I'd even say it's exactly what pip-tools as a project tries to protect against in the first place! Hmm. The `--upgrade` fix was a fix for a different problem. This poses an interesting challenge…

**Comment by jbbarth** [comment]
Confirmed here too, we had Django upgraded to 1.9.x while it was actually locked to 1.8.3 in our requirements.in file, and we were upgrading a specific package that didn't lock the dependency properly. Maybe it has something to do with case, as in said package, the requirement was on `django`, not `Django`. Not sure.

I'd suggest you prune pip-tools 1.4.3 if you cannot fix it soon because it breaks one of the fundamental behaviors that make pip-tools so awesome (and I mean it in a big way, you made our lives far easier, thanks!! :-))

Good luck, happy to help if I can, let me know.

**Comment by nvie** [comment]
I'm indeed going to revert 1.4.3 to be equal to 1.4.2 first thing as soon as I'm behind a computer (which should be within an hour).

**Comment by nvie** [comment]
This should now be fixed in 1.4.4. Thanks for catching this one! I'll see if I can work out a fix in 1.4.5 for the original problem without introducing this behaviour :relaxed:

**Comment by jbbarth** [comment]
Great, thanks a lot!

**Comment by syphar** [comment]
thanks @nvie
